exclude:
  - aws-s3-enable-bucket-logging
  - aws-s3-enable-versioning
  - aws-rds-enable-performance-insights
  - aws-eks-enable-control-plane-logging

severity_overrides:
  aws-s3-encryption-customer-key: LOW
  aws-rds-encrypt-instance-storage-data: MEDIUM