apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easybuybd-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/subrotosharma/easybuybd-ecommerce.git
    targetRevision: develop
    path: helm/easybuybd
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: easybuybd-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m